/* eslint-disable */
// This file is auto-generated by the Amplify CLI and should not be edited manually

export const getJob = /* GraphQL */ `
  query GetJob($id: ID!) {
    getJob(id: $id) {
      id
      jobNumber
      jobName
      clientName
      status
      createdAt
      updatedAt
      materials {
        items {
          id
          materialIdentifier
          description
          materialType
          systemType
          status
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;

export const listJobs = /* GraphQL */ `
  query ListJobs(
    $filter: ModelJobFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listJobs(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        jobNumber
        jobName
        clientName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const jobsByJobNumber = /* GraphQL */ `
  query JobsByJobNumber(
    $jobNumber: String!
    $sortDirection: ModelSortDirection
    $filter: ModelJobFilterInput
    $limit: Int
    $nextToken: String
  ) {
    jobsByJobNumber(
      jobNumber: $jobNumber
      sortDirection: $sortDirection
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        jobNumber
        jobName
        clientName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const getMaterial = /* GraphQL */ `
  query GetMaterial($id: ID!) {
    getMaterial(id: $id) {
      id
      jobId
      materialIdentifier
      description
      materialType
      systemType
      locationLevel
      locationZone
      status
      qrCodeData
      quantityEstimated
      unitOfMeasure
      detailDrawingId
      createdBy
      lastUpdatedBy
      createdAt
      updatedAt
      job {
        id
        jobNumber
        jobName
        status
      }
      history {
        items {
          id
          materialId
          timestamp
          userId
          action
          fieldName
          oldValue
          newValue
          notes
          location
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;

export const listMaterials = /* GraphQL */ `
  query ListMaterials(
    $filter: ModelMaterialFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listMaterials(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        jobId
        materialIdentifier
        description
        materialType
        systemType
        status
        qrCodeData
        quantityEstimated
        unitOfMeasure
        createdAt
        updatedAt
        job {
          id
          jobNumber
          jobName
        }
      }
      nextToken
    }
  }
`;

export const materialsByJob = /* GraphQL */ `
  query MaterialsByJob(
    $jobId: ID!
    $materialIdentifier: ModelStringKeyConditionInput
    $sortDirection: ModelSortDirection
    $filter: ModelMaterialFilterInput
    $limit: Int
    $nextToken: String
  ) {
    materialsByJob(
      jobId: $jobId
      materialIdentifier: $materialIdentifier
      sortDirection: $sortDirection
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        jobId
        materialIdentifier
        description
        materialType
        systemType
        status
        qrCodeData
        quantityEstimated
        unitOfMeasure
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const materialsByStatus = /* GraphQL */ `
  query MaterialsByStatus(
    $status: MaterialStatus!
    $createdAt: ModelStringKeyConditionInput
    $sortDirection: ModelSortDirection
    $filter: ModelMaterialFilterInput
    $limit: Int
    $nextToken: String
  ) {
    materialsByStatus(
      status: $status
      createdAt: $createdAt
      sortDirection: $sortDirection
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        jobId
        materialIdentifier
        description
        materialType
        systemType
        status
        createdAt
        updatedAt
        job {
          id
          jobNumber
          jobName
        }
      }
      nextToken
    }
  }
`;

export const materialByQrCode = /* GraphQL */ `
  query MaterialByQrCode(
    $qrCodeData: String!
    $id: ModelIDKeyConditionInput
    $sortDirection: ModelSortDirection
    $filter: ModelMaterialFilterInput
    $limit: Int
    $nextToken: String
  ) {
    materialByQrCode(
      qrCodeData: $qrCodeData
      id: $id
      sortDirection: $sortDirection
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        jobId
        materialIdentifier
        description
        materialType
        systemType
        locationLevel
        locationZone
        status
        qrCodeData
        quantityEstimated
        unitOfMeasure
        createdAt
        updatedAt
        job {
          id
          jobNumber
          jobName
          status
        }
      }
      nextToken
    }
  }
`;

export const getMaterialHistory = /* GraphQL */ `
  query GetMaterialHistory($id: ID!) {
    getMaterialHistory(id: $id) {
      id
      materialId
      timestamp
      userId
      action
      fieldName
      oldValue
      newValue
      notes
      location
      createdAt
      updatedAt
      material {
        id
        materialIdentifier
        description
        status
      }
    }
  }
`;

export const listMaterialHistories = /* GraphQL */ `
  query ListMaterialHistories(
    $filter: ModelMaterialHistoryFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listMaterialHistories(
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        materialId
        timestamp
        userId
        action
        fieldName
        oldValue
        newValue
        notes
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const getMaterialsCountByStatus = /* GraphQL */ `
  query GetMaterialsCountByStatus {
    materialsByStatus(status: "ESTIMATED", limit: 0) {
      nextToken
      estimatedCount: items { id }
    }
    
    materialsByStatus(status: "DETAILED", limit: 0) {
      nextToken
      detailedCount: items { id }
    }
    
    materialsByStatus(status: "RELEASED_TO_FAB", limit: 0) {
      nextToken
      releasedCount: items { id }
    }
    
    materialsByStatus(status: "IN_FABRICATION", limit: 0) {
      nextToken
      inFabCount: items { id }
    }
    
    materialsByStatus(status: "FABRICATED", limit: 0) {
      nextToken
      fabricatedCount: items { id }
    }
    
    materialsByStatus(status: "SHIPPED_TO_FIELD", limit: 0) {
      nextToken
      shippedCount: items { id }
    }
    
    materialsByStatus(status: "RECEIVED_ON_SITE", limit: 0) {
      nextToken
      receivedCount: items { id }
    }
    
    materialsByStatus(status: "INSTALLED", limit: 0) {
      nextToken
      installedCount: items { id }
    }
  }
`; 