/* eslint-disable */
// This file is auto-generated by the Amplify CLI and should not be edited manually

export const onCreateMaterial = /* GraphQL */ `
  subscription OnCreateMaterial($jobId: ID) {
    onCreateMaterial(jobId: $jobId) {
      id
      jobId
      materialIdentifier
      description
      materialType
      systemType
      locationLevel
      locationZone
      status
      qrCodeData
      createdAt
      updatedAt
      job {
        id
        jobNumber
        jobName
      }
    }
  }
`;

export const onUpdateMaterial = /* GraphQL */ `
  subscription OnUpdateMaterial($jobId: ID) {
    onUpdateMaterial(jobId: $jobId) {
      id
      jobId
      materialIdentifier
      description
      materialType
      systemType
      locationLevel
      locationZone
      status
      qrCodeData
      createdAt
      updatedAt
      job {
        id
        jobNumber
        jobName
      }
    }
  }
`;

export const onDeleteMaterial = /* GraphQL */ `
  subscription OnDeleteMaterial {
    onDeleteMaterial {
      id
      jobId
    }
  }
`;

export const onCreateJob = /* GraphQL */ `
  subscription OnCreateJob {
    onCreateJob {
      id
      jobNumber
      jobName
      clientName
      status
      createdAt
      updatedAt
    }
  }
`;

export const onUpdateJob = /* GraphQL */ `
  subscription OnUpdateJob {
    onUpdateJob {
      id
      jobNumber
      jobName
      clientName
      status
      createdAt
      updatedAt
    }
  }
`;

export const onDeleteJob = /* GraphQL */ `
  subscription OnDeleteJob {
    onDeleteJob {
      id
    }
  }
`; 