version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: ./backend
      target: development
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/service_booking?schema=public
      - MONGODB_URI=mongodb://mongo:27017/service_booking
      - JWT_SECRET=development_jwt_secret
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  # Frontend service
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=service_booking
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB database
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=service_booking
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: 